server.port=8080

# apiKey?????git
ai.model.bailian.codeplan.apiKey=sk-sp-221bc09518b1471a97583324df0e6752
ai.model.bailian.apiKey=sk-4002d569ac4b4d56892150f82cddfc41
ai.model.deepseek.apiKey=sk-c0087ab2eb03480b95e39bf4ef394d44

ai.rag.withInMemoryEmbeddingStore.switch=true

# MyBatis Configuration
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.rz.langchain.demo.server.mapper

# SQLite DataSource Configuration
spring.datasource.url=jdbc:sqlite:/Users/00545579/Documents/tools/chroma/data/chroma.sqlite3
spring.datasource.driver-class-name=org.sqlite.JDBC
